# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "rake", "~> 13.0"
  gem "rake-compiler", "~> 1.2"
  gem "rb_sys", "~> 0.9"
end

group :test do
  gem "rspec", "~> 3.12"
end

group :lint do
  gem "rubocop", "~> 1.75"
end

group :benchmark do
  gem "json-schema", "~> 6.1"
  gem "json_schemer", "~> 2.5"
  gem "rj_schema", "~> 1.0"
end
